spring.application.name=Collabapp

spring.data.mongodb.uri=mongodb+srv://Quant:d6dtK4fLqnKEGxxr@cluster0.2zexqm3.mongodb.net/collabapp?retryWrites=true&w=majority

#JWT
jwt.secret=3f8a2c1e9d7b4f6a0e5c8d2b1a9f3e7c4d6b8a0f2e1c9d7b5a3f8e2c4d6b087
jwt.access-token-expiry=300000
jwt.refresh-token-expiry=604800000